# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/549/bin/cmake

# The command to remove a file.
RM = /snap/cmake/549/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drimec/projects/kassy_42

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drimec/projects/kassy_42

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/549/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/549/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drimec/projects/kassy_42/CMakeFiles /home/drimec/projects/kassy_42//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drimec/projects/kassy_42/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named 42sh

# Build rule for target.
42sh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 42sh
.PHONY : 42sh

# fast build rule for target.
42sh/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/build
.PHONY : 42sh/fast

src/ast/ast.o: src/ast/ast.c.o

.PHONY : src/ast/ast.o

# target to build an object file
src/ast/ast.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/ast.c.o
.PHONY : src/ast/ast.c.o

src/ast/ast.i: src/ast/ast.c.i

.PHONY : src/ast/ast.i

# target to preprocess a source file
src/ast/ast.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/ast.c.i
.PHONY : src/ast/ast.c.i

src/ast/ast.s: src/ast/ast.c.s

.PHONY : src/ast/ast.s

# target to generate assembly for a file
src/ast/ast.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/ast/ast.c.s
.PHONY : src/ast/ast.c.s

src/execution/execution.o: src/execution/execution.c.o

.PHONY : src/execution/execution.o

# target to build an object file
src/execution/execution.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/execution/execution.c.o
.PHONY : src/execution/execution.c.o

src/execution/execution.i: src/execution/execution.c.i

.PHONY : src/execution/execution.i

# target to preprocess a source file
src/execution/execution.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/execution/execution.c.i
.PHONY : src/execution/execution.c.i

src/execution/execution.s: src/execution/execution.c.s

.PHONY : src/execution/execution.s

# target to generate assembly for a file
src/execution/execution.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/execution/execution.c.s
.PHONY : src/execution/execution.c.s

src/grammar/rule_and_or.o: src/grammar/rule_and_or.c.o

.PHONY : src/grammar/rule_and_or.o

# target to build an object file
src/grammar/rule_and_or.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_and_or.c.o
.PHONY : src/grammar/rule_and_or.c.o

src/grammar/rule_and_or.i: src/grammar/rule_and_or.c.i

.PHONY : src/grammar/rule_and_or.i

# target to preprocess a source file
src/grammar/rule_and_or.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_and_or.c.i
.PHONY : src/grammar/rule_and_or.c.i

src/grammar/rule_and_or.s: src/grammar/rule_and_or.c.s

.PHONY : src/grammar/rule_and_or.s

# target to generate assembly for a file
src/grammar/rule_and_or.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_and_or.c.s
.PHONY : src/grammar/rule_and_or.c.s

src/grammar/rule_command.o: src/grammar/rule_command.c.o

.PHONY : src/grammar/rule_command.o

# target to build an object file
src/grammar/rule_command.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_command.c.o
.PHONY : src/grammar/rule_command.c.o

src/grammar/rule_command.i: src/grammar/rule_command.c.i

.PHONY : src/grammar/rule_command.i

# target to preprocess a source file
src/grammar/rule_command.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_command.c.i
.PHONY : src/grammar/rule_command.c.i

src/grammar/rule_command.s: src/grammar/rule_command.c.s

.PHONY : src/grammar/rule_command.s

# target to generate assembly for a file
src/grammar/rule_command.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_command.c.s
.PHONY : src/grammar/rule_command.c.s

src/grammar/rule_compound.o: src/grammar/rule_compound.c.o

.PHONY : src/grammar/rule_compound.o

# target to build an object file
src/grammar/rule_compound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_compound.c.o
.PHONY : src/grammar/rule_compound.c.o

src/grammar/rule_compound.i: src/grammar/rule_compound.c.i

.PHONY : src/grammar/rule_compound.i

# target to preprocess a source file
src/grammar/rule_compound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_compound.c.i
.PHONY : src/grammar/rule_compound.c.i

src/grammar/rule_compound.s: src/grammar/rule_compound.c.s

.PHONY : src/grammar/rule_compound.s

# target to generate assembly for a file
src/grammar/rule_compound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_compound.c.s
.PHONY : src/grammar/rule_compound.c.s

src/grammar/rule_do_group.o: src/grammar/rule_do_group.c.o

.PHONY : src/grammar/rule_do_group.o

# target to build an object file
src/grammar/rule_do_group.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_do_group.c.o
.PHONY : src/grammar/rule_do_group.c.o

src/grammar/rule_do_group.i: src/grammar/rule_do_group.c.i

.PHONY : src/grammar/rule_do_group.i

# target to preprocess a source file
src/grammar/rule_do_group.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_do_group.c.i
.PHONY : src/grammar/rule_do_group.c.i

src/grammar/rule_do_group.s: src/grammar/rule_do_group.c.s

.PHONY : src/grammar/rule_do_group.s

# target to generate assembly for a file
src/grammar/rule_do_group.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_do_group.c.s
.PHONY : src/grammar/rule_do_group.c.s

src/grammar/rule_element.o: src/grammar/rule_element.c.o

.PHONY : src/grammar/rule_element.o

# target to build an object file
src/grammar/rule_element.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_element.c.o
.PHONY : src/grammar/rule_element.c.o

src/grammar/rule_element.i: src/grammar/rule_element.c.i

.PHONY : src/grammar/rule_element.i

# target to preprocess a source file
src/grammar/rule_element.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_element.c.i
.PHONY : src/grammar/rule_element.c.i

src/grammar/rule_element.s: src/grammar/rule_element.c.s

.PHONY : src/grammar/rule_element.s

# target to generate assembly for a file
src/grammar/rule_element.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_element.c.s
.PHONY : src/grammar/rule_element.c.s

src/grammar/rule_else.o: src/grammar/rule_else.c.o

.PHONY : src/grammar/rule_else.o

# target to build an object file
src/grammar/rule_else.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_else.c.o
.PHONY : src/grammar/rule_else.c.o

src/grammar/rule_else.i: src/grammar/rule_else.c.i

.PHONY : src/grammar/rule_else.i

# target to preprocess a source file
src/grammar/rule_else.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_else.c.i
.PHONY : src/grammar/rule_else.c.i

src/grammar/rule_else.s: src/grammar/rule_else.c.s

.PHONY : src/grammar/rule_else.s

# target to generate assembly for a file
src/grammar/rule_else.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_else.c.s
.PHONY : src/grammar/rule_else.c.s

src/grammar/rule_for.o: src/grammar/rule_for.c.o

.PHONY : src/grammar/rule_for.o

# target to build an object file
src/grammar/rule_for.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_for.c.o
.PHONY : src/grammar/rule_for.c.o

src/grammar/rule_for.i: src/grammar/rule_for.c.i

.PHONY : src/grammar/rule_for.i

# target to preprocess a source file
src/grammar/rule_for.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_for.c.i
.PHONY : src/grammar/rule_for.c.i

src/grammar/rule_for.s: src/grammar/rule_for.c.s

.PHONY : src/grammar/rule_for.s

# target to generate assembly for a file
src/grammar/rule_for.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_for.c.s
.PHONY : src/grammar/rule_for.c.s

src/grammar/rule_funcdec.o: src/grammar/rule_funcdec.c.o

.PHONY : src/grammar/rule_funcdec.o

# target to build an object file
src/grammar/rule_funcdec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_funcdec.c.o
.PHONY : src/grammar/rule_funcdec.c.o

src/grammar/rule_funcdec.i: src/grammar/rule_funcdec.c.i

.PHONY : src/grammar/rule_funcdec.i

# target to preprocess a source file
src/grammar/rule_funcdec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_funcdec.c.i
.PHONY : src/grammar/rule_funcdec.c.i

src/grammar/rule_funcdec.s: src/grammar/rule_funcdec.c.s

.PHONY : src/grammar/rule_funcdec.s

# target to generate assembly for a file
src/grammar/rule_funcdec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_funcdec.c.s
.PHONY : src/grammar/rule_funcdec.c.s

src/grammar/rule_if.o: src/grammar/rule_if.c.o

.PHONY : src/grammar/rule_if.o

# target to build an object file
src/grammar/rule_if.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_if.c.o
.PHONY : src/grammar/rule_if.c.o

src/grammar/rule_if.i: src/grammar/rule_if.c.i

.PHONY : src/grammar/rule_if.i

# target to preprocess a source file
src/grammar/rule_if.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_if.c.i
.PHONY : src/grammar/rule_if.c.i

src/grammar/rule_if.s: src/grammar/rule_if.c.s

.PHONY : src/grammar/rule_if.s

# target to generate assembly for a file
src/grammar/rule_if.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_if.c.s
.PHONY : src/grammar/rule_if.c.s

src/grammar/rule_list.o: src/grammar/rule_list.c.o

.PHONY : src/grammar/rule_list.o

# target to build an object file
src/grammar/rule_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_list.c.o
.PHONY : src/grammar/rule_list.c.o

src/grammar/rule_list.i: src/grammar/rule_list.c.i

.PHONY : src/grammar/rule_list.i

# target to preprocess a source file
src/grammar/rule_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_list.c.i
.PHONY : src/grammar/rule_list.c.i

src/grammar/rule_list.s: src/grammar/rule_list.c.s

.PHONY : src/grammar/rule_list.s

# target to generate assembly for a file
src/grammar/rule_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_list.c.s
.PHONY : src/grammar/rule_list.c.s

src/grammar/rule_pipeline.o: src/grammar/rule_pipeline.c.o

.PHONY : src/grammar/rule_pipeline.o

# target to build an object file
src/grammar/rule_pipeline.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_pipeline.c.o
.PHONY : src/grammar/rule_pipeline.c.o

src/grammar/rule_pipeline.i: src/grammar/rule_pipeline.c.i

.PHONY : src/grammar/rule_pipeline.i

# target to preprocess a source file
src/grammar/rule_pipeline.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_pipeline.c.i
.PHONY : src/grammar/rule_pipeline.c.i

src/grammar/rule_pipeline.s: src/grammar/rule_pipeline.c.s

.PHONY : src/grammar/rule_pipeline.s

# target to generate assembly for a file
src/grammar/rule_pipeline.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_pipeline.c.s
.PHONY : src/grammar/rule_pipeline.c.s

src/grammar/rule_prefix.o: src/grammar/rule_prefix.c.o

.PHONY : src/grammar/rule_prefix.o

# target to build an object file
src/grammar/rule_prefix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_prefix.c.o
.PHONY : src/grammar/rule_prefix.c.o

src/grammar/rule_prefix.i: src/grammar/rule_prefix.c.i

.PHONY : src/grammar/rule_prefix.i

# target to preprocess a source file
src/grammar/rule_prefix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_prefix.c.i
.PHONY : src/grammar/rule_prefix.c.i

src/grammar/rule_prefix.s: src/grammar/rule_prefix.c.s

.PHONY : src/grammar/rule_prefix.s

# target to generate assembly for a file
src/grammar/rule_prefix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_prefix.c.s
.PHONY : src/grammar/rule_prefix.c.s

src/grammar/rule_redir.o: src/grammar/rule_redir.c.o

.PHONY : src/grammar/rule_redir.o

# target to build an object file
src/grammar/rule_redir.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_redir.c.o
.PHONY : src/grammar/rule_redir.c.o

src/grammar/rule_redir.i: src/grammar/rule_redir.c.i

.PHONY : src/grammar/rule_redir.i

# target to preprocess a source file
src/grammar/rule_redir.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_redir.c.i
.PHONY : src/grammar/rule_redir.c.i

src/grammar/rule_redir.s: src/grammar/rule_redir.c.s

.PHONY : src/grammar/rule_redir.s

# target to generate assembly for a file
src/grammar/rule_redir.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_redir.c.s
.PHONY : src/grammar/rule_redir.c.s

src/grammar/rule_shell_command.o: src/grammar/rule_shell_command.c.o

.PHONY : src/grammar/rule_shell_command.o

# target to build an object file
src/grammar/rule_shell_command.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_shell_command.c.o
.PHONY : src/grammar/rule_shell_command.c.o

src/grammar/rule_shell_command.i: src/grammar/rule_shell_command.c.i

.PHONY : src/grammar/rule_shell_command.i

# target to preprocess a source file
src/grammar/rule_shell_command.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_shell_command.c.i
.PHONY : src/grammar/rule_shell_command.c.i

src/grammar/rule_shell_command.s: src/grammar/rule_shell_command.c.s

.PHONY : src/grammar/rule_shell_command.s

# target to generate assembly for a file
src/grammar/rule_shell_command.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_shell_command.c.s
.PHONY : src/grammar/rule_shell_command.c.s

src/grammar/rule_simple_command.o: src/grammar/rule_simple_command.c.o

.PHONY : src/grammar/rule_simple_command.o

# target to build an object file
src/grammar/rule_simple_command.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_simple_command.c.o
.PHONY : src/grammar/rule_simple_command.c.o

src/grammar/rule_simple_command.i: src/grammar/rule_simple_command.c.i

.PHONY : src/grammar/rule_simple_command.i

# target to preprocess a source file
src/grammar/rule_simple_command.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_simple_command.c.i
.PHONY : src/grammar/rule_simple_command.c.i

src/grammar/rule_simple_command.s: src/grammar/rule_simple_command.c.s

.PHONY : src/grammar/rule_simple_command.s

# target to generate assembly for a file
src/grammar/rule_simple_command.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_simple_command.c.s
.PHONY : src/grammar/rule_simple_command.c.s

src/grammar/rule_until.o: src/grammar/rule_until.c.o

.PHONY : src/grammar/rule_until.o

# target to build an object file
src/grammar/rule_until.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_until.c.o
.PHONY : src/grammar/rule_until.c.o

src/grammar/rule_until.i: src/grammar/rule_until.c.i

.PHONY : src/grammar/rule_until.i

# target to preprocess a source file
src/grammar/rule_until.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_until.c.i
.PHONY : src/grammar/rule_until.c.i

src/grammar/rule_until.s: src/grammar/rule_until.c.s

.PHONY : src/grammar/rule_until.s

# target to generate assembly for a file
src/grammar/rule_until.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_until.c.s
.PHONY : src/grammar/rule_until.c.s

src/grammar/rule_while.o: src/grammar/rule_while.c.o

.PHONY : src/grammar/rule_while.o

# target to build an object file
src/grammar/rule_while.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_while.c.o
.PHONY : src/grammar/rule_while.c.o

src/grammar/rule_while.i: src/grammar/rule_while.c.i

.PHONY : src/grammar/rule_while.i

# target to preprocess a source file
src/grammar/rule_while.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_while.c.i
.PHONY : src/grammar/rule_while.c.i

src/grammar/rule_while.s: src/grammar/rule_while.c.s

.PHONY : src/grammar/rule_while.s

# target to generate assembly for a file
src/grammar/rule_while.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/grammar/rule_while.c.s
.PHONY : src/grammar/rule_while.c.s

src/lexer/lexer.o: src/lexer/lexer.c.o

.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.o
.PHONY : src/lexer/lexer.c.o

src/lexer/lexer.i: src/lexer/lexer.c.i

.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.i
.PHONY : src/lexer/lexer.c.i

src/lexer/lexer.s: src/lexer/lexer.c.s

.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/lexer.c.s
.PHONY : src/lexer/lexer.c.s

src/lexer/token.o: src/lexer/token.c.o

.PHONY : src/lexer/token.o

# target to build an object file
src/lexer/token.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.o
.PHONY : src/lexer/token.c.o

src/lexer/token.i: src/lexer/token.c.i

.PHONY : src/lexer/token.i

# target to preprocess a source file
src/lexer/token.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.i
.PHONY : src/lexer/token.c.i

src/lexer/token.s: src/lexer/token.c.s

.PHONY : src/lexer/token.s

# target to generate assembly for a file
src/lexer/token.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/lexer/token.c.s
.PHONY : src/lexer/token.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/main.c.s
.PHONY : src/main.c.s

src/option/option.o: src/option/option.c.o

.PHONY : src/option/option.o

# target to build an object file
src/option/option.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/option/option.c.o
.PHONY : src/option/option.c.o

src/option/option.i: src/option/option.c.i

.PHONY : src/option/option.i

# target to preprocess a source file
src/option/option.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/option/option.c.i
.PHONY : src/option/option.c.i

src/option/option.s: src/option/option.c.s

.PHONY : src/option/option.s

# target to generate assembly for a file
src/option/option.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/option/option.c.s
.PHONY : src/option/option.c.s

src/prompt/prompt.o: src/prompt/prompt.c.o

.PHONY : src/prompt/prompt.o

# target to build an object file
src/prompt/prompt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/prompt/prompt.c.o
.PHONY : src/prompt/prompt.c.o

src/prompt/prompt.i: src/prompt/prompt.c.i

.PHONY : src/prompt/prompt.i

# target to preprocess a source file
src/prompt/prompt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/prompt/prompt.c.i
.PHONY : src/prompt/prompt.c.i

src/prompt/prompt.s: src/prompt/prompt.c.s

.PHONY : src/prompt/prompt.s

# target to generate assembly for a file
src/prompt/prompt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/prompt/prompt.c.s
.PHONY : src/prompt/prompt.c.s

src/read/read.o: src/read/read.c.o

.PHONY : src/read/read.o

# target to build an object file
src/read/read.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/read/read.c.o
.PHONY : src/read/read.c.o

src/read/read.i: src/read/read.c.i

.PHONY : src/read/read.i

# target to preprocess a source file
src/read/read.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/read/read.c.i
.PHONY : src/read/read.c.i

src/read/read.s: src/read/read.c.s

.PHONY : src/read/read.s

# target to generate assembly for a file
src/read/read.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/read/read.c.s
.PHONY : src/read/read.c.s

src/structures/structures.o: src/structures/structures.c.o

.PHONY : src/structures/structures.o

# target to build an object file
src/structures/structures.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/structures/structures.c.o
.PHONY : src/structures/structures.c.o

src/structures/structures.i: src/structures/structures.c.i

.PHONY : src/structures/structures.i

# target to preprocess a source file
src/structures/structures.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/structures/structures.c.i
.PHONY : src/structures/structures.c.i

src/structures/structures.s: src/structures/structures.c.s

.PHONY : src/structures/structures.s

# target to generate assembly for a file
src/structures/structures.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/structures/structures.c.s
.PHONY : src/structures/structures.c.s

src/tools/tools.o: src/tools/tools.c.o

.PHONY : src/tools/tools.o

# target to build an object file
src/tools/tools.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/tools/tools.c.o
.PHONY : src/tools/tools.c.o

src/tools/tools.i: src/tools/tools.c.i

.PHONY : src/tools/tools.i

# target to preprocess a source file
src/tools/tools.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/tools/tools.c.i
.PHONY : src/tools/tools.c.i

src/tools/tools.s: src/tools/tools.c.s

.PHONY : src/tools/tools.s

# target to generate assembly for a file
src/tools/tools.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/tools/tools.c.s
.PHONY : src/tools/tools.c.s

src/variable/variable.o: src/variable/variable.c.o

.PHONY : src/variable/variable.o

# target to build an object file
src/variable/variable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/variable/variable.c.o
.PHONY : src/variable/variable.c.o

src/variable/variable.i: src/variable/variable.c.i

.PHONY : src/variable/variable.i

# target to preprocess a source file
src/variable/variable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/variable/variable.c.i
.PHONY : src/variable/variable.c.i

src/variable/variable.s: src/variable/variable.c.s

.PHONY : src/variable/variable.s

# target to generate assembly for a file
src/variable/variable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/42sh.dir/build.make CMakeFiles/42sh.dir/src/variable/variable.c.s
.PHONY : src/variable/variable.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... check"
	@echo "... doc"
	@echo "... 42sh"
	@echo "... src/ast/ast.o"
	@echo "... src/ast/ast.i"
	@echo "... src/ast/ast.s"
	@echo "... src/execution/execution.o"
	@echo "... src/execution/execution.i"
	@echo "... src/execution/execution.s"
	@echo "... src/grammar/rule_and_or.o"
	@echo "... src/grammar/rule_and_or.i"
	@echo "... src/grammar/rule_and_or.s"
	@echo "... src/grammar/rule_command.o"
	@echo "... src/grammar/rule_command.i"
	@echo "... src/grammar/rule_command.s"
	@echo "... src/grammar/rule_compound.o"
	@echo "... src/grammar/rule_compound.i"
	@echo "... src/grammar/rule_compound.s"
	@echo "... src/grammar/rule_do_group.o"
	@echo "... src/grammar/rule_do_group.i"
	@echo "... src/grammar/rule_do_group.s"
	@echo "... src/grammar/rule_element.o"
	@echo "... src/grammar/rule_element.i"
	@echo "... src/grammar/rule_element.s"
	@echo "... src/grammar/rule_else.o"
	@echo "... src/grammar/rule_else.i"
	@echo "... src/grammar/rule_else.s"
	@echo "... src/grammar/rule_for.o"
	@echo "... src/grammar/rule_for.i"
	@echo "... src/grammar/rule_for.s"
	@echo "... src/grammar/rule_funcdec.o"
	@echo "... src/grammar/rule_funcdec.i"
	@echo "... src/grammar/rule_funcdec.s"
	@echo "... src/grammar/rule_if.o"
	@echo "... src/grammar/rule_if.i"
	@echo "... src/grammar/rule_if.s"
	@echo "... src/grammar/rule_list.o"
	@echo "... src/grammar/rule_list.i"
	@echo "... src/grammar/rule_list.s"
	@echo "... src/grammar/rule_pipeline.o"
	@echo "... src/grammar/rule_pipeline.i"
	@echo "... src/grammar/rule_pipeline.s"
	@echo "... src/grammar/rule_prefix.o"
	@echo "... src/grammar/rule_prefix.i"
	@echo "... src/grammar/rule_prefix.s"
	@echo "... src/grammar/rule_redir.o"
	@echo "... src/grammar/rule_redir.i"
	@echo "... src/grammar/rule_redir.s"
	@echo "... src/grammar/rule_shell_command.o"
	@echo "... src/grammar/rule_shell_command.i"
	@echo "... src/grammar/rule_shell_command.s"
	@echo "... src/grammar/rule_simple_command.o"
	@echo "... src/grammar/rule_simple_command.i"
	@echo "... src/grammar/rule_simple_command.s"
	@echo "... src/grammar/rule_until.o"
	@echo "... src/grammar/rule_until.i"
	@echo "... src/grammar/rule_until.s"
	@echo "... src/grammar/rule_while.o"
	@echo "... src/grammar/rule_while.i"
	@echo "... src/grammar/rule_while.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/lexer/token.o"
	@echo "... src/lexer/token.i"
	@echo "... src/lexer/token.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/option/option.o"
	@echo "... src/option/option.i"
	@echo "... src/option/option.s"
	@echo "... src/prompt/prompt.o"
	@echo "... src/prompt/prompt.i"
	@echo "... src/prompt/prompt.s"
	@echo "... src/read/read.o"
	@echo "... src/read/read.i"
	@echo "... src/read/read.s"
	@echo "... src/structures/structures.o"
	@echo "... src/structures/structures.i"
	@echo "... src/structures/structures.s"
	@echo "... src/tools/tools.o"
	@echo "... src/tools/tools.i"
	@echo "... src/tools/tools.s"
	@echo "... src/variable/variable.o"
	@echo "... src/variable/variable.i"
	@echo "... src/variable/variable.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

